### ISSUE TITLE
Axis drift when jogging

### ISSUE THREAD

**Issue by machinekoder** [UTNuclearRoboticsPublic/jog_arm#17]
I noticed a slight drift in the axis positions not being jogged when jogging a single axis. The effect is not big, but it adds up after some time. The problem is clearly visible when printing out `MoveGroupCommander().get_current_pose()`

**Comment by AndyZe** [comment]
I think this will be difficult to avoid because the Jacobian matrix will almost always contain nonzero values. It could be due to rounding error or joint angles that aren't quite zero/perpendicular. For example, this 3x3 matrix almost has eigenvalues of {1, 3, -2}, but there are enough nonzero components to cause some drift.

[ 1   0.0003  -0.0001;
0.0003  3.00008  0.0004;
0.001  0.0006  -2.000004]

I guess the best way to avoid this would be a dedicated joint jogger, like your other ticket asks for.
