### ISSUE TITLE
Robot model is loaded twice

### ISSUE THREAD

**Issue by machinekoder** [UTNuclearRoboticsPublic/jog_arm#57]
Robot model is loaded by collision check and the jogging thread, this adds unnecessary loading time.

**Comment by AndyZe** [comment]
Attempted to fix this today by moving robot_model_loader into the JogROSInterface class. If I do that, it must be static, since it's used in creation of the threads. However, robot_model_loader creates its own NodeHandle which requires ros::init() first, so it can't be static. I'm out of ideas for now.

**Comment by AndyZe** [comment]
Found a way to do this with pointers. 6e93371

**Comment by machinekoder** [comment]
Yes, looks good. Great that you use smart pointers btw.
